
spring:
  application:
    name: Api Server 2
  profiles:
    active: local
  jpa:
    open-in-view: false
    database: default
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/app2_db?createDatabaseIfNotExist=true
    hikari:
      connection-timeout: 10000
      idle-timeout: 60000
      max-lifetime: 600000
      maximum-pool-size: ${DB_POOL_MAX_SIZE:10}
      minimum-idle: ${DB_POOL_MIN_IDLE:5}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    virtual-host: ${RABBITMQ_DEFAULT_VHOST:/app-msg-broker}
  flyway:
    out-of-order: true

server:
  port: 8082
  servlet:
    context-path: /app2

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics


greeting:
  text: ${greeting.title}

debug: true

logging:
  level:
    org.springframework: DEBUG